### ISSUE TITLE
Question about formatting

### ISSUE THREAD

**Issue by jay-sridharan** [RafaGago/mini-async-log-c#7]
I just had a small question on a design decision: why did you choose to write your own serialization rather than use an existing library like `fmtlib`, or simply `vsnprintf`? Was this to support lazy evaluation?

Thank you for all the work on the library - it looks great!

**Comment by RafaGago** [comment]
Thanks!

- As you say, it is lazily evaluated, no formatting happens on the calling thread but on the background one. All the message-related information is passed on a single chunk of memory. The format string is passed as a pointer.

- This a plain C logging library with C++ wrappers, that rules out fmtlib. It probably also predates fmtlib, at least fmtlib wasn't popular when this was written.
